### PR TITLE
Sidebar GA notice

### PR DESCRIPTION
**Pull request by esethna**
Needs a link to docs or blog post.

@amyblais please make sure we merge for the v5.32 release

### CODE REVIEW

**Comment by esethna** [comment]
@amyblais I added the link to the blog post that will go out before release, also edited the time window so it appears exactly on the 16th (ie we want this to be the first thing users see when they get the upgrade)

**Comment by amyblais** [comment]
@esethna Thanks, is this ready for QA testing?

**Review by amyblais — DISMISSED** [review]

**Comment by esethna** [comment]
@ogi-m yes but please note that the blog link wont work until it's published on the 15th

**Comment by esethna** [comment]
@ogi-m ping on this as we want to ensure the notice is live as soon as v5.32 is launched

**Review by ogi-m — APPROVED** [review]
Tested and passed 👍🏻

**Pull request merged**
