### PR TITLE
Update action link URL for URL tracking

### PR DESCRIPTION
**Pull request by esethna**
Updated action URL to https://mattermost.com/download?inapp-notice=true#mattermostApps so BizOps teeam can track direct traffic from the notice cc// @jasonblais

### CODE REVIEW

**Comment by esethna** [comment]
@jasonblais if we use `https://mattermost.com/download?inapp-notice=true&serverid=%3Cserverid%3E#mattermostApps` will server ID get populated automatically?

**Review by ogi-m — APPROVED** [review]
Tested in master, LGTM 👍

**Comment by esethna** [comment]
@jasonblais merging this change now, but we can change again if we want to add the server ID tracking

**Comment by jasonblais** [comment]
@esethna thanks!

**Pull request merged**
