### PR TITLE
CRT GA notices

### PR DESCRIPTION
**Pull request by esethna**
Adding 4 new notices for CRT GA:

1. On-prem + cloud instances set to "Disabled": Encourage **admins** to enable CRT
2. On-prem + cloud instances set to "Default_off": encourage **admins** to enable CRT by default
3. On-prem + Cloud users in servers set to "default_on": Introduce all users to CRT and let them know they can disable it.
4. On-prem + Cloud users in servers set to "always_on": Introduce all users to CRT

### CODE REVIEW

**Comment by esethna** [comment]
cc// @ogi-m can you please help share a screenshot of each notice as part of testing, and also ensure all links and conditions are working as expected? Thanks!

**Comment by esethna** [comment]
@ogi-m can you help prioritize a review here? Thanks!

**Comment by ogi-m** [comment]
@esethna @amyblais I can't get the notice for "Default off" to trigger, trying to figure out why...

The others three look good:
1. Disabled:

image

3. Default_on:

image

4. Always_on:

image


Note that I've only tested against on-prem, as the cloud test server got deleted. I've created a new one and I'm waiting on Cloud SRE to update the config on it.

**Comment by esethna** [comment]
@ogi-m please approve once cloud is tested and validated, then we can merge

**Comment by ogi-m** [comment]
@esethna @amyblais Verified all notices are working as expected on cloud 👍🏻

**Review by ogi-m — APPROVED** [review]

**Comment by esethna** [comment]
@ogi-m I haven't seen this notice on our community server yet, is that expected? Note we have it set to default_on so I would have expected to get notice # 3

**Comment by ogi-m** [comment]
@esethna I think that's because it's on master:

image

**Comment by ogi-m** [comment]
@esethna It's running `master` / Enterprise Edition which is an on-prem image. For cloud it would be `cloud` / "Mattermost Cloud"

image

**Comment by esethna** [comment]
Got it, thanks (so it reports itself as an "on-prem" instance for the purpose of notices and doesn't match the version check, hence we'll never see notices on community unless there's no version check)

**Pull request merged**
