### PR TITLE
v9.1 Notice

### PR DESCRIPTION
**Pull request by amyblais**
#### Summary
 - In-product notice for v9.1 release.

#### Screenshots of the modals or screens in all target clients (required)
 - The server upgrade image should display https://github.com/mattermost/notices/blob/master/images/server_upgrade.png along with the text from https://github.com/mattermost/notices/pull/374/files#diff-11766faeb8c25f77d7dbf8e61fd0e9fc8cd1a08858d6b1f8867715a570bfd9d9R131

#### Test environment (required)
 - [x] Server versions - v9.0 and v9.1

#### Test steps and expectation (required)
 - Spin up a v9.0 server - the notice should appear.
 - Spin up a v9.1 server - the notice should not appear.

### CODE REVIEW

**Review by yasserfaraazkhan — DISMISSED** [review]
tested on 9.0 -> notification appears
tested on 9.1 -> notification Does not appears

Screenshot 2023-10-17 at 4 37 20 PM

**Review by wiersgallak — COMMENTED** [review]
Wonder if we want to link people to the blog post instead of the docs? https://mattermost.com/blog/mattermost-v9-1-is-now-available/

**Comment by amyblais** [comment]
@wiersgallak The latest commit has a link to the blog https://github.com/mattermost/notices/pull/374/files.

**Comment by amyblais** [comment]
@yasserfaraazkhan I re-requested your review because I committed minor updates, and your previous approval got dismissed.

**Review by yasserfaraazkhan — APPROVED** [review]
Screenshot 2023-10-24 at 12 35 30 AM
tested on 9.0 to get the notice and verified the links
on 9.1 it didn't appear as expected

**Pull request merged**
