### PR TITLE
v7.5 Notice

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Review by wuwinson — APPROVED** [review]
LGTM!

**Comment by esethna** [comment]
Adding @nab-77 to review and see if we want to make a change to this monthly notice template. 

For example, some things that come to mind:

- The CTA is to the blog post, is that what we want? 
- Do we want to add tracking to the links to see click through rates

**Comment by nab-77** [comment]
@esethna I think the min indeed is tracking. I've requested a link for this notice.

**Review by nab-77 — CHANGES_REQUESTED** [review]

**Review by nab-77 — DISMISSED** [review]

**Review by ogi-m — APPROVED** [review]

**Comment by amyblais** [comment]
@ogi-m The approvals got removed, so I just added you to give this an approval (no testing is needed).

**Review by ogi-m — APPROVED** [review]

**Pull request merged**
