### PR TITLE
Remove old notices for custom statuses and channel sidebar

### PR DESCRIPTION
**Pull request by jasonblais**
Propose removing old notices which were released more than a year ago

This is in preparation to submitting a notice for Cloud freemium launch to self-hosted instances

### CODE REVIEW

**Review by ogi-m — APPROVED** [review]

**Comment by jasonblais** [comment]
Thanks @ogi-m for reviewing, what's the merge process for PRs in notices.json?

**Review by ogi-m — APPROVED** [review]

**Comment by ogi-m** [comment]
@jasonblais There was a failed check blocking the merge because of a syntax error, it's fixed now.

PMs should have permissions to merge, can you try now?
Or @esethna. could you please merge?

**Comment by jasonblais** [comment]
@ogi-m thanks! Looks like I can merge, merging now

**Comment by jasonblais** [comment]
@ogi-m After merging, I just got an in-product notice about custom statuses to my Cloud workspace. Is that a potential bug?

image

**Comment by jasonblais** [comment]
@ogi-m I got it a second time in my Cloud workspace just now

image

**Comment by ogi-m** [comment]
@jasonblais That definitely should not be happening. I can't repro on my cloud production instance.

**Comment by esethna** [comment]
@jasonblais @ogi-m the server only checks the notices configuration once per day, so it may have checked before this change was merged.

Did you see it twice with the same account on the same server? If so that part sounds like a bug.

**Pull request merged**
