### PR TITLE
v4.5 desktop upgrade notice

### PR DESCRIPTION
**Pull request by esethna**
@jgilliam17 @ogi-m I'm submitting this PR is against the "release" branch since it's a production notice. Can you guys please test this notice by adding it to the master branch, then verifying it in your notice testing environments? Once tested on the master branch, please add your approval on the PR so we can merge it to the release branch and test it out in production tomorrow (community-daily & community-release)

### CODE REVIEW

**Comment by esethna** [comment]
@jaydeland the build seems to be stuck? ^

**Comment by jaydeland** [comment]
> @jaydeland the build seems to be stuck? ^

Will check on it later this evening

**Comment by esethna** [comment]
Added a label for "Editor" review to review and approve text

**Review by amyblais — APPROVED** [review]

**Comment by jgilliam17** [comment]
Tested, looks good to merge.
- Notice appears as expected on desktop versions <4.5. Tested on 4.4.2 and 4.3.2 - notice received. Download button opens Mattermost App downloads page.
- Notice is correctly not appearing for 4.5, 4.6 and also for users on the webapp.
Screen Shot 2020-10-14 at 6 58 19 PM

**Review by jgilliam17 — APPROVED** [review]

**Comment by esethna** [comment]
@jaydeland please merge once you've figured out the build issue, thanks!

**Comment by esethna** [comment]
Closing due to build issues, reopened here: https://github.com/mattermost/notices/pull/46

**Pull request closed without merging**
