### PR TITLE
Server v5.31 Notice

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Review by esethna — APPROVED** [review]
@ogi-m can you share a screenshot of the notice from testing?

**Review by esethna — APPROVED** [review]

**Comment by ogi-m** [comment]
LGTM! 

Screenshot (138)

**Review by ogi-m — APPROVED** [review]

**Comment by amyblais** [comment]
@ogi-m I just realized that the promotional text for the release announce was slightly tweaked, which I've edited here in my latest commit. Does it need to be re-tested?

**Review by ogi-m — APPROVED** [review]
@amyblais That's fine as it's just a small change to the text and the conditions haven't changed.

**Review by esethna — APPROVED** [review]

**Pull request merged**
