### PR TITLE
Update desktop upgrade notice for v4.6

### PR DESCRIPTION
**Pull request by esethna**
Update desktop upgrade notice for v4.6

### CODE REVIEW

**Comment by esethna** [comment]
@amyblais can we please add a step to the desktop release process at ship day to update the desktop upgrade notice as done in this PR?

Let's also add a step to the server release process to do the same (starting in v5.29).

**Review by ogi-m — APPROVED** [review]
Tested the notice in master. Got it on 4.5 as expected and not on 4.6

Destkop

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
> @amyblais can we please add a step to the desktop release process at ship day to update the desktop upgrade notice as done in this PR?
> 
> Let's also add a step to the server release process to do the same (starting when we ship v5.29).

Yeah I'll update the checklist and open a ticket.

**Comment by amyblais** [comment]
> @amyblais can we please add a step to the desktop release process at ship day to update the desktop upgrade notice as done in this PR?
> 
> Let's also add a step to the server release process to do the same (starting when we ship v5.29).

@esethna Should the checklist item in general be: 1. Create a ticket for Eric **OR** 2. Ping Eric in a channel?

Or is this a checklist item for me to do?

**Comment by esethna** [comment]
@amyblais I would propose this is a checklist item for the release manager to do. Since it would basically be updating the existing notices with minor changes (as done in this PR). Of course feel free to ping me as needed for help or guidance.

**Pull request merged**
